name: GDScript / Lint

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Setup gdtoolkit
        uses: Scony/godot-gdscript-toolkit@09af1747fd66629af601b1f14d1ac24203358686

      - name: Lint
        run: gdlint exercises
